# Generated by Django 4.2.4 on 2023-09-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0006_remove_borrowrequest_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_age',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Возраст автора'),
        ),
    ]
